/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package meujframe;


/**
 *
 * @author drago
 */
public class MeuJFrame1 extends javax.swing.JFrame {

    /**
     * Creates new form MeuJFrame1
     */
    public MeuJFrame1() {
        setUndecorated(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Painel_foto_login = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Painel_login = new javax.swing.JPanel();
        Label_usuario = new javax.swing.JLabel();
        Label_senha = new javax.swing.JLabel();
        Label_login = new javax.swing.JLabel();
        Campo_usuario = new javax.swing.JTextField();
        Campo_senha = new javax.swing.JPasswordField();
        Label_cadastro = new javax.swing.JLabel();
        Botao_cadastro = new javax.swing.JButton();
        Botao_entrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setLocation(new java.awt.Point(50, 50));
        setMaximumSize(new java.awt.Dimension(530, 560));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Painel_foto_login.setBackground(new java.awt.Color(255, 255, 255));
        Painel_foto_login.setForeground(new java.awt.Color(255, 255, 255));
        Painel_foto_login.setPreferredSize(new java.awt.Dimension(200, 600));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meujframe/Images/usuario-removebg-preview-removebg-preview.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meujframe/Images/icone_fechar.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Painel_foto_loginLayout = new javax.swing.GroupLayout(Painel_foto_login);
        Painel_foto_login.setLayout(Painel_foto_loginLayout);
        Painel_foto_loginLayout.setHorizontalGroup(
            Painel_foto_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_foto_loginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Painel_foto_loginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(14, 14, 14))
        );
        Painel_foto_loginLayout.setVerticalGroup(
            Painel_foto_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Painel_foto_loginLayout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(197, 197, 197))
        );

        getContentPane().add(Painel_foto_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 200, 600));

        Painel_login.setBackground(new java.awt.Color(102, 0, 153));
        Painel_login.setPreferredSize(new java.awt.Dimension(330, 600));
        Painel_login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label_usuario.setFont(new java.awt.Font("Square721 BT", 0, 24)); // NOI18N
        Label_usuario.setForeground(new java.awt.Color(255, 255, 255));
        Label_usuario.setText("Usuário:");
        Painel_login.add(Label_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 164, 100, 25));

        Label_senha.setFont(new java.awt.Font("Square721 BT", 0, 24)); // NOI18N
        Label_senha.setForeground(new java.awt.Color(255, 255, 255));
        Label_senha.setText("Senha:");
        Painel_login.add(Label_senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 213, -1, 25));

        Label_login.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        Label_login.setForeground(new java.awt.Color(255, 255, 255));
        Label_login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_login.setText("Spá");
        Painel_login.add(Label_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 45, 219, -1));

        Campo_usuario.setActionCommand("<Not Set>");
        Campo_usuario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Campo_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Campo_usuarioActionPerformed(evt);
            }
        });
        Painel_login.add(Campo_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 164, 130, 25));

        Campo_senha.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Campo_senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Campo_senhaActionPerformed(evt);
            }
        });
        Painel_login.add(Campo_senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 213, 130, 25));

        Label_cadastro.setForeground(new java.awt.Color(102, 255, 102));
        Label_cadastro.setText("Não tem cadastro?");
        Painel_login.add(Label_cadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 301, -1, -1));

        Botao_cadastro.setText("Cadastre-se");
        Botao_cadastro.setBorder(null);
        Botao_cadastro.setBorderPainted(false);
        Botao_cadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Botao_cadastroMouseClicked(evt);
            }
        });
        Botao_cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_cadastroActionPerformed(evt);
            }
        });
        Painel_login.add(Botao_cadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 297, 85, 24));

        Botao_entrar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Botao_entrar.setText("Entrar");
        Botao_entrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        Botao_entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_entrarActionPerformed(evt);
            }
        });
        Painel_login.add(Botao_entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 100, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meujframe/Images/instragram.png"))); // NOI18N
        Painel_login.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 90, 82));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meujframe/Images/Cadeado.png"))); // NOI18N
        Painel_login.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 204, -1, 39));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meujframe/Images/usuario_login-removebg-preview.png"))); // NOI18N
        Painel_login.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 152, -1, 40));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Odesyle Moreira");
        Painel_login.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, -1, -1));

        getContentPane().add(Painel_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 600));

        getAccessibleContext().setAccessibleName("Painel_Principal");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Campo_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Campo_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Campo_usuarioActionPerformed

    private void Campo_senhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Campo_senhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Campo_senhaActionPerformed

    private void Botao_cadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_cadastroActionPerformed
        Cadastro cadastro = new Cadastro();
        cadastro.setVisible(true);
        
    // TODO add your handling code here:      
    }//GEN-LAST:event_Botao_cadastroActionPerformed

    private void Botao_entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_entrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Botao_entrarActionPerformed

    private void Botao_cadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Botao_cadastroMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Botao_cadastroMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        dispose();
    // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MeuJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MeuJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MeuJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MeuJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MeuJFrame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Botao_cadastro;
    private javax.swing.JButton Botao_entrar;
    private javax.swing.JPasswordField Campo_senha;
    private javax.swing.JTextField Campo_usuario;
    private javax.swing.JLabel Label_cadastro;
    private javax.swing.JLabel Label_login;
    private javax.swing.JLabel Label_senha;
    private javax.swing.JLabel Label_usuario;
    private javax.swing.JPanel Painel_foto_login;
    private javax.swing.JPanel Painel_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
